# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tamboon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tamboon
  pod 'SDWebImage'

  target 'tamboonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tamboonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
